services:
  postgres-master:
    image: postgres:14
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - master-pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  postgres-replica1:
    image: postgres:14
    container_name: postgres-replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REPLICA_ID: 1
    ports:
      - "5433:5432"
    volumes:
      - replica1-pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb-replica.d:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    depends_on:
      postgres-master:
        condition: service_healthy

  postgres-replica2:
    image: postgres:14
    container_name: postgres-replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REPLICA_ID: 2
    ports:
      - "5434:5432"
    volumes:
      - replica2-pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb-replica.d:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    depends_on:
      postgres-master:
        condition: service_healthy

networks:
  postgres-network:

volumes:
  master-pg-data:
  replica1-pg-data:
  replica2-pg-data: